channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=25.1.1
- pip:
  - mlflow==2.22.0
  - cffi==1.17.1
  - cloudpickle==3.1.0
  - defusedxml==0.7.1
  - graphviz==0.20.3
  - imbalanced-learn==0.12.4
  - lightgbm==4.5.0
  - matplotlib==3.9.2
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==6.0.0
  - pyarrow==20.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
